'use strict';

const express = require('express');
const router = express.Router();
const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');
const { Pool } = require('pg');

// Database Connection Setup
// Note: In production, move these credentials to your .env file
const pool = new Pool({
    user: process.env.DB_USER || 'postgres',
    host: process.env.DB_HOST || 'localhost',
    database: 'credentials_db', // As per your setup
    password: process.env.DB_PASSWORD || 'mrrobot',
    port: process.env.DB_PORT || 5432,
});

const JWT_SECRET = process.env.JWT_SECRET || 'your_super_secret_key_for_pending_services';

// ==========================================
// 1. REGISTRATION ROUTE
// ==========================================
router.post('/register', async (req, res) => {
    const { username, email, password } = req.body;

    // Basic validation
    if (!username || !email || !password) {
        return res.status(400).json({ success: false, error: 'All fields are required' });
    }

    try {
        // Hash the password before storing
        const saltRounds = 12;
        const hashedPassword = await bcrypt.hash(password, saltRounds);

        // Insert into your credentials_table
        // user_id is auto-generated by your uuid_generate_v4() default
        const query = `
            INSERT INTO credentials_table (username, email, password_hash)
            VALUES ($1, $2, $3)
            RETURNING user_id, username, email;
        `;
        const values = [username, email, hashedPassword];
        
        const result = await pool.query(query, values);

        res.status(201).json({
            success: true,
            message: 'User created successfully',
            user: result.rows[0]
        });

    } catch (err) {
        console.error('Registration Error:', err.message);
        // Check for unique constraint violation (e.g., email already exists)
        if (err.code === '23505') {
            return res.status(409).json({ success: false, error: 'Email or Username already exists' });
        }
        res.status(500).json({ success: false, error: 'Internal server error during registration' });
    }
});

// ==========================================
// 2. LOGIN ROUTE
// ==========================================
router.post('/login', async (req, res) => {
    const { identifier, password } = req.body; // identifier can be email or username

    if (!identifier || !password) {
        return res.status(400).json({ success: false, error: 'Identification and password required' });
    }

    try {
        // Look up user by email OR username
        const query = `SELECT * FROM credentials_table WHERE email = $1 OR username = $1`;
        const result = await pool.query(query, [identifier]);

        if (result.rows.length === 0) {
            return res.status(401).json({ success: false, error: 'Invalid credentials' });
        }

        const user = result.rows[0];

        // Compare hashed password
        const isMatch = await bcrypt.compare(password, user.password_hash);

        if (!isMatch) {
            return res.status(401).json({ success: false, error: 'Invalid credentials' });
        }

        // Create JWT Token
        const token = jwt.sign(
            { id: user.user_id, username: user.username, role: user.user_role },
            JWT_SECRET,
            { expiresIn: '24h' }
        );

        // Return exactly what your frontend main.js expects
        res.json({
            success: true,
            token: token,
            user: {
                id: user.user_id,
                username: user.username,
                role: user.user_role
            }
        });

    } catch (err) {
        console.error('Login Error:', err.message);
        res.status(500).json({ success: false, error: 'Internal server error during login' });
    }
});

module.exports = router;